Repository python-validators/validators, pull requests merged in 2023-09, with the labels that each got.

#291 Add note about ValidationFailure to ValidationError in changes.md
  CHANGES.md
Labels: documentation

#294 fix: simple hostname validation regex
  .gitignore
  pdm.lock
  pyproject.toml
  python/requirements.mkdocs.txt
  python/requirements.sphinx.txt
  python/requirements.tooling.txt
  src/validators/hostname.py
Labels: dependencies, bugfix

#295 fix: strict CIDR IP validation; bump version
  CHANGES.md
  SECURITY.md
  pyproject.toml
  src/validators/__init__.py
  src/validators/ip_address.py
  tests/test_ip_address.py
Labels: open for review, maintenance, bugfix

#297 fix: Valid URLs failing validation - query and fragment parts
  src/validators/url.py
  tests/test_url.py
Labels: maintenance, bugfix

#301 fix: bug in `between` module
  .gitignore
  pdm.lock
  pyproject.toml
  python/genreq.ps1
  python/genreq.sh
  python/requirements.mkdocs.txt
  python/requirements.sphinx.txt
  python/requirements.tooling.txt
  src/validators/between.py
  tests/test_between.py
Labels: maintenance, dependencies, bugfix
